import{a as m,S as c,i as a}from"./assets/vendor-BMHzDZyJ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const p="https://pixabay.com",h="/api/",g="50282426-bcbed3422443d463b1ec5299f";function y(s){const o=new URLSearchParams({key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),n=`${p}${h}?${o}`;return m.get(n).then(r=>r.data.hits).catch(r=>{throw console.error("Помилка при запиті до Pixabay:",r),r})}const l=document.querySelector(".gallery"),u=document.querySelector(".loader-container");let b=new c(".gallery a");function L(s){const o=s.map(({webformatURL:n,largeImageURL:r,tags:e,likes:t,views:i,comments:d,downloads:f})=>`
      <li class="gallery-item">
        <a href="${r}">
          <img src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${d}</p>
          <p><b>Downloads:</b> ${f}</p>
        </div>
      </li>`).join("");l.insertAdjacentHTML("beforeend",o),b.refresh()}function w(){l.innerHTML=""}function P(){u.classList.remove("hidden")}function S(){u.classList.add("hidden")}const $=document.querySelector(".gallery"),q=document.querySelector(".form");q.addEventListener("submit",s=>{s.preventDefault();const o=s.target.elements["search-text"].value.trim();if(o===""){a.show({title:"Error",message:"Please enter a search query!",position:"topRight",color:"red"});return}w(),P(),y(o).then(n=>{if(n.length===0)a.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"});else{const r=L(n);$.insertAdjacentHTML("beforeend",r),new c(".gallery-item a",{captionsData:"alt",captionDelay:250})}}).catch(n=>{a.show({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",color:"red"}),console.error(n)}).finally(()=>{S()}),s.target.reset()});
//# sourceMappingURL=index.js.map
